### ISSUE TITLE
Specify authentication fields in the documentation

### ISSUE THREAD

**Issue by ToX82** [Xety/Cake3-CookieAuth#6]
I have an application using email and password for authentication, and I've had a few problems trying to integrate Cake3-CookieAuth. After some investigation, I have found out that you need to tell CookieAuth which fields are in use:

    $this->loadComponent('Auth', [
        'authenticate' => [
            'Form' => [
                'fields' => ['username' => 'email']
            ],
            'Xety/Cake3CookieAuth.Cookie' => [
                'fields' => ['username' => 'email'] // this is what I was missing
            ]
        ],
        ...
    ]);

I think that this should be explained in the README...

**Comment by Moutard3** [comment]
👍 Was missing the same thing

**Comment by Xety** [comment]
The fields name are the default one used by CakePHP itself. But i will add it to the Readme.

**Comment by PhantomWatson** [comment]
This doesn't appear to have been added to the readme.

**Comment by Xety** [comment]
@PhantomWatson I added it in this commit : https://github.com/Xety/Cake3-CookieAuth/commit/b1f899eba842e43584caee2c873ec852bfa180fa#diff-04c6e90faac2675aa89e2176d2eec7d8R31. You can find it in the `Configuration` part : https://github.com/Xety/Cake3-CookieAuth#configuration

I don't want to set all the configuration options in the Readme, due to the change that Cake can do. So i prefer to redirect people to the officiel Cake doc.

**Comment by PhantomWatson** [comment]
Ohhh, I understand now. Thanks!
